---
title: "EDA.Rmd"
output: html_document
date: "2023-10-05"
---

The purpose of this Rmarkdown is to track function development and demonstrate their use

# Load Libraries

```{r}
library(tidyverse, quietly = TRUE)
library(readxl)
```

# Download data function

```{r}
install_avonet <- function(filename){
  
  cat("Downloading AvoNet...\n")
  
  download.file(url = "https://figshare.com/ndownloader/files/34480856?private_link=b990722d72a26b5bfead", destfile = filename, mode = "wb")

  }
```

```{r}
install_avonet(filename = "raw_data/AVONET Supplementary dataset 1.xlsx")
```

# Load AvoNet

```{r}
load_avonet <- function() {

  # store avonet as list of tibbles
  
  avonet <- list()
  
  names <- c("metadata", "birdlife", "ebird", "birdtree", 5, "raw_data", "mass_sources", "data_sources", "measurers", 10, 11)
    
  for (i in 1:11) {
  x <- setNames(list(read_xlsx("raw_data/AVONET Supplementary dataset 1.xlsx", sheet = i)), names[i])
  avonet <- append(avonet, x)
  }
  
  # Rename variables
  
  # Make variables lowercase across tibbles
  
  colnames(avonet$metadata) <- tolower(colnames(avonet$metadata))
  colnames(avonet$birdlife) <- tolower(colnames(avonet$birdlife))
  colnames(avonet$ebird) <- tolower(colnames(avonet$ebird))
  colnames(avonet$birdtree) <- tolower(colnames(avonet$birdtree))
  colnames(avonet$`5`) <- tolower(colnames(avonet$`5`))
  colnames(avonet$raw_data) <- tolower(colnames(avonet$raw_data))
  colnames(avonet$mass_sources) <- tolower(colnames(avonet$mass_sources))
  colnames(avonet$data_sources) <- tolower(colnames(avonet$data_sources))
  colnames(avonet$measurers) <- tolower(colnames(avonet$measurers))
  colnames(avonet$`10`) <- tolower(colnames(avonet$`10`))
  colnames(avonet$`11`) <- tolower(colnames(avonet$`11`))
  
  # Make variable character values lowercase in metadata tibble -> method adapted from StackOverflow (https://stackoverflow.com/questions/50615116/renaming-character-variables-in-a-column-in-data-frame-r)
  
  variable_old_name <- c(avonet$metadata$variable)

  variable_new_name <- c(tolower(avonet$metadata$variable))

  variable_lookup <- setNames(variable_new_name, variable_old_name)

  avonet$metadata$variable <- as.character(variable_lookup[avonet$metadata$variable])
  
  # Remove space in 'variable types' in metadata tibble
  
  avonet$metadata <- avonet$metadata %>% 
    rename(variable.types = `variable types`)
  
  # Return avonet
  
  return(avonet)

}
```

```{r}
avonet <- load_avonet()
```


