---
title: "Final Project (Working Title)"
author: "Charlotte Drury U6603688"
date: "04/10/2023"
output:  
    html_document:
        toc: true
        toc_depth: 4
        theme: cosmo
        number_sections: false
        toc_float: true
        highlight: pygments
        fig_width: 8
        fig_height: 4
---

# Word/figure count

words: 550

figures: 0

# Location on GitHub

https://github.com/DruryCF/DS4B-final-project

# Data Description

The AvoNet database contains functional trait data for 90,020 individual birds representing 11,009 extant species sampled from 181 countries (Tobias et al., 2022). It includes 11 continuous morphological traits (such as beak and wing dimensions; and tail, tarsus, and body size), 6 ecological variables, as well as range size, and geographic location. The database also includes species averages according to three different taxonomy classifications to enable integration with other databases.

# Questions/Aims

Aim: to build an R-package to interface with AvoNet

* Build functions to:
    + install and load data
    + tidy data
    + clean data (As AvoNet is a single release, it can be pre-cleaned)
    + facilitate Exploratory Data Analysis (EDA)

Justification: 

AvoNet is stored across 9 related excel spreadsheets making it difficult to explore and interact with. Other datasets stored similarly (e.g. AusTraits, Atlas of Living Australia) have dedicated R-packages to streamline their use (Falster et al., 2021; Westgate et al., 2023). Some of AvoNet is incorporated in the 'traitdata' package, however this (at the time of writing) is only trait data on a single member per species according to the BirdLife taxonomy classification (RS-eco, 2022). An R-package that interfaces with the entirety of AvoNet would facilitate EDA and aid in addressing specific research questions.

# Raw data



# Data wrangling



# Sanity checks



# Addressing the questions/aims



# References

Falster, D., Gallagher, R., Wenk, E.H. et al. (2021). AusTraits, a curated plant trait database for the Australian flora. _Sci Data_ 8, 254. https://doi.org/10.1038/s41597-021-01006-6

RS-eco (2022). _traitdata: Easy access to various ecological trait data_. R package version 0.0.1, https://github.com/RS-eco/traitdata

Tobias, J.A., Sheard, C., Pigot, A.L. et al. (2022). AVONET: morphological, ecological and geographical data for all birds. _Ecology Letters_, 25(3), 581–597. https://doi.org/10.1111/ele.13898

Westgate, M., Kellie, D., Stevenson, M., Newman, P. (2023). _galah: Biodiversity Data from the Living Atlas Community_. R package version 1.5.3, https://CRAN.R-project.org/package=galah

